project:
  type: website

website:
  title: "Cardiff Transplant"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: agenda.qmd
        text: Agenda
      - href: speakers.qmd
        text: Speakers
      - href: about.qmd
        text: About
  site-url: https://cardifftransplant.org    
  page-footer: 
    left: <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/) by [L Szabo](https://lszabo.me)</span>
    
# right: 
    #   - icon: github
    #     text: "Code Repo"
      
    # background: "#2780e3"
  
  favicon: images/icon_kidney.jpg
  # image: images/davinci.png
  twitter-card: 
    title: 8^th^ Cardiff Transplant Symposium
    description: Looking to the future of Organ Donation and Transplantation
    creator: "@drszabolaszlo"
    image: images/banner2.png
  open-graph:
    title: 8^th^ Cardiff Transplant Symposium
    description: Looking to the future of Organ Donation and Transplantation
    locale: en_UK
    site-name: Cardiff Transplant Symposium
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

